version: "3.7"
services:
  vscode:
#    image: mfaizan95/latex-docker:latest # comment this line if you want to build dockerfile
    build: . # uncomment this line if you want to build dockerfile
    volumes:
      - ../:/workspace
      - ~/.ssh:/home/vscode/.ssh:ro
      - ~/.ssh:/root/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    entrypoint: zsh -c "while sleep 1000; do :; done"
